force-app/main/default/objects/Data_Quality_Config__mdt/Data_Quality_Config__mdt.object-meta.xml
<CustomObject>
    <label>Data Quality Config</label>
    <pluralLabel>Data Quality Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Quality_Config__mdt/fields/CheckType__c.field-meta.xml
<CustomField>
    <fullName>CheckType__c</fullName>
    <description>This chektype represents method of class to be run</description>
    <label>CheckType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>runReqFieldChecks</fullName>
                <default>true</default>
                <label>runReqFieldChecks</label>
            </value>
            <value>
                <fullName>runEmailandPhoneChecks</fullName>
            </value>
            <value>
                <fullName>searchForDuplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Quality_Config__mdt/fields/EmailFieldAPINames__c.field-meta.xml
<CustomField>
    <fullName>EmailFieldAPINames__c</fullName>
    <label>EmailFieldAPINames</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Quality_Config__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
                <default>true</default>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Quality_Config__mdt/fields/PhonefieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>PhonefieldAPIName__c</fullName>
    <label>PhonefieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Quality_Config__mdt/fields/Required_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Required_Field_Api_Name__c</fullName>
    <label>Required Field Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Quality_Score__c/Data_Quality_Score__c.object-meta.xml
<CustomObject>
    <label>Data Quality Score</label>
    <pluralLabel>Data Quality Scores</pluralLabel>
    <nameField>
        <label>Score Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Text</type>
        <length>80</length>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Text</type>
        <length>80</length>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <type>Percent</type>
        <precision>3</precision>
        <scale>2</scale>
    </fields>
    <fields>
        <fullName>Analysis_Date__c</fullName>
        <label>Analysis Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>LongTextArea</type>
        <length>32768</length>
    </fields>
</CustomObject>

force-app/main/default/classes/Dataqualityscheduler.cls
global class Dataqualityscheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        List<Data_Quality_Score__c> lsdqs =  new List<Data_Quality_Score__c>();
        String query = 'SELECT Id, CheckType__c, EmailFieldAPINames__c,FieldName__c,Object_API_Name__c,PhonefieldAPIName__c,Required_Field_Api_Name__c FROM Data_Quality_Config__mdt';
        List<Data_Quality_Config__mdt> records = Database.query(query);
        Map<String,List<String>> objVsreqFieldsMap = new Map<String,List<String>>();
        Map<String,List<String>> ObjVsEmailMap = new Map<String,List<String>>();
        Map<String,List<String>> objVsphnMap = new Map<String,List<String>>();
        Set<String> objectsName = new Set<String>();
        for(Data_Quality_Config__mdt mrec:records){
           if(mrec.CheckType__c == 'searchForDuplicate'){
               lsdqs.add(DataQualityValidator.searchForDuplicate(mrec.Object_API_Name__c,mrec.FieldName__c));
            }
            if(mrec.CheckType__c == 'runReqFieldChecks'){
                if(!objVsreqFieldsMap.containsKey(mrec.Object_API_Name__c)){
                    objVsreqFieldsMap.put(mrec.Object_API_Name__c,new List<String>());
                }
                objVsreqFieldsMap.get(mrec.Object_API_Name__c).add(mrec.Required_Field_Api_Name__c);
            }
            if(mrec.CheckType__c == 'runEmailandPhoneChecks'){
                objectsName.add(mrec.Object_API_Name__c);
                 if(!ObjVsEmailMap.containsKey(mrec.Object_API_Name__c)){
                    ObjVsEmailMap.put(mrec.Object_API_Name__c,new List<String>());
                }
                ObjVsEmailMap.get(mrec.Object_API_Name__c).add(mrec.EmailFieldAPINames__c);   
                
                if(!objVsphnMap.containsKey(mrec.Object_API_Name__c)){
                    objVsphnMap.put(mrec.Object_API_Name__c,new List<String>());
                }
                objVsphnMap.get(mrec.Object_API_Name__c).add(mrec.PhonefieldAPIName__c); 
                
            }
        }
        
        if(objVsreqFieldsMap.Size()>0){
            for(String objApiname:objVsreqFieldsMap.keySet()){
                if(objVsreqFieldsMap.containsKey(objApiname))
                    lsdqs.addall(DataQualityValidator.runReqFieldChecks(objApiname,objVsreqFieldsMap.get(objApiname)));
            }
        }
        for(String objapiname:objectsName){
          lsdqs.addall( DataQualityValidator.runEmailandPhoneChecks(objapiname,ObjVsEmailMap.get(objapiname),objVsphnMap.get(objapiname)));
        }
        if(lsdqs.size()>0){
           insert lsdqs; 
        }
    }
       
}